name: dynamic_function
description: "dynamic_function package project"
version: 1.0.1
homepage:
repository: https://github.com/lang-library/dart-dynamic-function

environment:
  sdk: ^3.7.2

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
